# Generated by Django 2.2.2 on 2019-06-16 05:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_auto_20190610_2140'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jersey',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=5),
        ),
    ]
