# Generated by Django 2.2.2 on 2019-06-16 05:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_auto_20190616_0511'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jersey',
            name='kit_type',
            field=models.CharField(max_length=5),
        ),
        migrations.AlterField(
            model_name='jersey',
            name='sleeve_length',
            field=models.CharField(max_length=1),
        ),
        migrations.AlterField(
            model_name='jersey',
            name='year',
            field=models.CharField(max_length=7),
        ),
    ]
