# Generated by Django 2.2.2 on 2019-06-16 05:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0004_auto_20190616_0513'),
    ]

    operations = [
        migrations.CreateModel(
            name='Teammate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('jersey', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.Jersey')),
            ],
        ),
    ]
