# Generated by Django 2.2.2 on 2019-06-16 05:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0005_teammate'),
    ]

    operations = [
        migrations.RenameField(
            model_name='teammate',
            old_name='name',
            new_name='last_name',
        ),
    ]
