# Generated by Django 2.2.2 on 2019-06-16 16:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0007_auto_20190616_1610'),
    ]

    operations = [
        migrations.RenameField(
            model_name='jersey',
            old_name='teammate',
            new_name='teammates',
        ),
    ]
